# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
encoding: utf-8
title: Leo Ferres' Home page
email: leoferres@gmail.com
email2: lferres@udd.cl
description: > # this means to ignore newlines until "baseurl:"
  Leo Ferres is a Research Professor of Computer Science at Universidad del Desarrollo, and a fellow of the Telefónica R+D Center in Santiago, Chile. His interests include big data, parallel computing, natural language processing and computational social science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://leoferres.github.io" # the base hostname & protocol for your site
twitter_username: leoferres
github_username:  leoferres

# Build settings
highlighter: rouge
markdown: kramdown
